@extends('layouts.app')@section('title','SobatAnak — Mom & Baby Care')@section('content')
<section class="hero-slider relative overflow-hidden bg-gradient-to-br from-[#D0F0ED] via-white to-[#FDECEA]">
    <div class="absolute top-10 right-20 w-64 h-64 rounded-full bg-[#4BBFB0]/10 blur-3xl"></div>
    <div class="hero-orb hero-orb-one"></div>
    <div class="hero-orb hero-orb-two"></div>
    <div class="max-w-7xl mx-auto px-6 md:px-12 py-12 md:py-16 relative">
        @php $slides=[
            ['Lovely Kids 🌟','Semua yang Si Kecil','Butuhkan Ada di Sini!','Produk bayi berkualitas tinggi — dari pakaian hingga mainan edukatif. Belanja dengan cinta, seperti kasih ibu.','Lihat Koleksi',route('products'),'https://images.unsplash.com/photo-1514090319495-53885bfc202f'],
            ['Produk Terbaik 🍼','Kualitas Premium untuk','Buah Hati Tercinta','Dipilih dengan cermat oleh para ahli parenting. Aman, nyaman, dan menyenangkan untuk tumbuh kembang si kecil.','Belanja Sekarang',route('products'),'https://img.rocket.new/generatedImages/rocket_gen_img_1598e07f6-1765125327744.png'],
            ['Main & Menang 🎮','Main Game, Kumpulkan','Poin & Tukar Hadiah!','Nikmati mini game seru, kumpulkan poin, dan tukarkan dengan voucher belanja menarik.','Main Sekarang',route('mini-games'),'https://img.rocket.new/generatedImages/rocket_gen_img_1eb162b6f-1766561509584.png']
        ]; @endphp
        <div class="hero-slide-stage min-h-[480px] md:min-h-[545px]">
            @foreach($slides as $idx=>$s)
            <div data-slide class="hero-slide {{ $idx===0 ? 'is-active' : '' }} grid grid-cols-1 md:grid-cols-2 gap-8 items-center">
                <div class="hero-copy">
                    <span class="text-coral font-black text-sm uppercase tracking-widest">— {{ $s[0] }}</span>
                    <h1 class="font-display hero-title mt-4">{{ $s[1] }}<br><span class="text-teal">{{ $s[2] }}</span></h1>
                    <p class="text-lg text-[#6B8A88] font-bold max-w-md mt-5">{{ $s[3] }}</p>
                    <div class="flex flex-wrap gap-3 mt-6"><a class="btn-pill btn-coral" href="{{ $s[5] }}">{{ $s[4] }} →</a><a class="btn-pill border-2 border-[#4BBFB0] text-teal" href="{{ route('mini-games') }}">🎮 Main & Poin</a></div>
                    <div class="flex gap-6 mt-6 font-black"><div>2.400+<br><small class="text-[#6B8A88]">Produk</small></div><div>50K+<br><small class="text-[#6B8A88]">Keluarga</small></div><div>⭐ 4.9<br><small class="text-[#6B8A88]">Rating</small></div></div>
                </div>
                <div class="relative hero-media-wrap">
                    <img class="hero-img w-full rounded-[2rem] shadow-2xl object-cover" src="{{ $s[6] }}" alt="SobatAnak slide">
                    <div class="float absolute bottom-5 left-5 bg-white/90 rounded-2xl px-4 py-3 shadow-xl font-black">🏆 Dipercaya 50.000+ Keluarga</div>
                </div>
            </div>
            @endforeach
        </div>
        <div class="hero-controls">
            <button data-prev class="hero-nav" aria-label="Slide sebelumnya">‹</button>
            <div class="hero-dots">@foreach($slides as $idx=>$s)<button data-dot="{{ $idx }}" class="hero-dot {{ $idx===0 ? 'is-active' : '' }}" aria-label="Pindah slide {{ $idx+1 }}"></button>@endforeach</div>
            <button data-next class="hero-nav" aria-label="Slide berikutnya">›</button>
        </div>
    </div>
</section>
<section class="py-16"><div class="max-w-7xl mx-auto px-6 md:px-12"><div class="flex items-end justify-between mb-9"><div><span class="uppercase tracking-widest text-[#6B8A88] font-bold text-xs">Pilihan Terbaik</span><h2 class="section-title font-display">Produk <span class="text-teal italic">Unggulan</span></h2></div><a class="font-black border-b" href="{{ route('products') }}">Lihat Semua Produk →</a></div><div class="grid grid-cols-1 md:grid-cols-3 gap-4">@foreach($products as $p)<div class="card reveal modal-card cursor-pointer" data-open-product data-id="{{ $p->id }}" data-name="{{ $p->name }}" data-category="{{ $p->category }}" data-price="{{ $p->price }}" data-rating="{{ $p->rating }}" data-sold="{{ $p->sold }}" data-image="{{ $p->image }}" data-badge="{{ $p->badge }}"><div class="relative"><img class="product-img w-full" src="{{ $p->image }}">@if($p->badge)<span class="badge">{{ $p->badge }}</span>@endif</div><div class="p-5"><p class="text-xs uppercase tracking-widest text-[#6B8A88] font-black">{{ $p->category }}</p><h3 class="font-display text-lg mt-1">{{ $p->name }}</h3><p class="text-sm text-[#6B8A88]">⭐ {{ $p->rating }} · {{ number_format($p->sold,0,',','.') }} terjual</p><div class="flex items-center justify-between mt-4"><b>Rp {{ number_format($p->price,0,',','.') }}</b><button data-buy data-product-id="{{ $p->id }}" class="btn-pill btn-coral text-xs py-2">+ Keranjang</button></div><button type="button" class="modal-read-more mt-3">Lihat detail produk →</button></div></div>@endforeach</div></div></section>
<section class="py-16 bg-[#F0FAF9]"><div class="max-w-7xl mx-auto px-6 md:px-12 grid md:grid-cols-2 gap-8 items-center"><div><span class="text-coral font-black uppercase tracking-widest text-xs">Points & Rewards</span><h2 class="section-title font-display mt-3">Main Game, Kumpulkan <span class="text-teal">Poin</span></h2><p class="text-[#6B8A88] font-bold mt-4">Poin tersimpan di browser dan bisa dipakai untuk menukar reward.</p><a class="btn-pill btn-coral mt-6" href="{{ route('mini-games') }}">Mulai Main 🎮</a></div><div class="grid gap-3">@foreach($rewards as $r)<div class="card p-5 flex justify-between items-center"><div><b>{{ $r->name }}</b><p class="text-sm text-[#6B8A88]">{{ $r->description }}</p></div><span class="font-black text-coral">{{ $r->points }} pts</span></div>@endforeach</div></div></section>
<section class="py-16"><div class="max-w-7xl mx-auto px-6 md:px-12"><h2 class="section-title font-display mb-8">Apa Kata <span class="text-teal">Mereka</span></h2><div class="grid md:grid-cols-3 gap-5">@foreach($testimonials as $t)<div class="card p-6"><p class="text-yellow-500">★★★★★</p><p class="text-[#6B8A88] my-4">“{{ $t->message }}”</p><b>{{ $t->name }}</b></div>@endforeach</div></div></section>
<section class="py-16 bg-white"><div class="max-w-7xl mx-auto px-6 md:px-12"><div class="flex justify-between mb-8"><h2 class="section-title font-display">Artikel <span class="text-teal">Parenting</span></h2><a class="font-black" href="{{ route('articles') }}">Semua Artikel →</a></div><div class="grid md:grid-cols-3 gap-5">@foreach($articles as $a)<article class="card modal-card cursor-pointer" data-open-article data-title="{{ $a->title }}" data-category="{{ $a->category_name }}" data-excerpt="{{ $a->excerpt }}" data-image="{{ $a->image }}" data-date="{{ $a->created_at ? $a->created_at->format('d M Y') : 'SobatAnak' }}"><img class="product-img w-full" src="{{ $a->image }}"><div class="p-5"><span class="text-coral font-black text-xs uppercase">{{ $a->category_name }}</span><h3 class="font-display text-xl mt-2">{{ $a->title }}</h3><p class="text-[#6B8A88] mt-2">{{ $a->excerpt }}</p><button type="button" class="modal-read-more mt-3">Baca ringkasan →</button></div></article>@endforeach</div></div></section>

<div class="info-modal" data-product-modal aria-hidden="true"><div class="info-modal-backdrop" data-modal-close></div><div class="info-modal-panel product-detail-panel" role="dialog" aria-modal="true"><button class="modal-close" data-modal-close aria-label="Tutup">×</button><div class="grid lg:grid-cols-[1fr_1.05fr] gap-6 items-stretch"><div class="modal-image-wrap"><img data-modal-product-image src="" alt="Detail produk"></div><div class="modal-content"><span class="modal-kicker" data-modal-product-category></span><h2 class="font-display modal-title" data-modal-product-name></h2><div class="flex flex-wrap gap-2 my-4"><span class="modal-chip" data-modal-product-rating></span><span class="modal-chip" data-modal-product-sold></span><span class="modal-chip" data-modal-product-badge></span></div><h3 class="modal-price" data-modal-product-price></h3><p class="modal-desc" data-modal-product-desc></p><div class="modal-benefits"><div><b>✨ Kelebihan</b><p>Aman, nyaman, dan cocok untuk kebutuhan harian bayi serta anak.</p></div><div><b>🧸 Cocok Untuk</b><p>Orang tua yang ingin produk praktis, berkualitas, dan mudah digunakan.</p></div><div><b>🛍️ Catatan</b><p>Tambahkan ke cart untuk lanjut ke halaman checkout khusus akun kamu.</p></div></div><div class="flex flex-wrap gap-3 mt-6"><button data-modal-product-buy class="btn-pill btn-coral">+ Masukkan Cart</button><a href="{{ route('cart.index') }}" class="btn-pill btn-teal">Lihat Cart</a></div></div></div></div></div>
<div class="info-modal" data-article-modal aria-hidden="true"><div class="info-modal-backdrop" data-modal-close></div><div class="info-modal-panel article-detail-panel" role="dialog" aria-modal="true"><button class="modal-close" data-modal-close aria-label="Tutup">×</button><div class="modal-article-hero"><img data-modal-article-image src="" alt="Detail artikel"></div><div class="modal-content article-modal-content"><span class="modal-kicker" data-modal-article-category></span><h2 class="font-display modal-title" data-modal-article-title></h2><p class="modal-meta">📅 <span data-modal-article-date></span> · ⏱️ 3 menit baca · SobatAnak Editorial</p><p class="modal-desc" data-modal-article-excerpt></p><div class="article-pop-grid"><div><b>Ringkasan</b><p data-modal-article-summary></p></div><div><b>Yang Dibahas</b><ul><li>Tips praktis untuk orang tua.</li><li>Hal penting yang perlu diperhatikan.</li><li>Rekomendasi kebiasaan baik di rumah.</li></ul></div><div><b>Catatan SobatAnak</b><p>Gunakan artikel ini sebagai panduan awal. Sesuaikan kembali dengan kebutuhan si kecil dan kondisi keluarga.</p></div></div></div></div></div>
@endsection